title: Rhys Cazenove
description: Software engineer based in London. Building digital products and platforms since 2001.
url: "https://blog.rhyscazenove.com"
baseurl: ""

# Build settings
markdown: kramdown
remote_theme: knhash/jekyllBear
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Permalink style
permalink: /:year/:month/:day/:title/

# Author
author:
  name: Rhys Cazenove

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_feed_layout: tag_feed
tag_feed_dir: tag

# Exclude from build
exclude:
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock
